//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 01:16:20 PM UTC 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enregistrementsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enregistrementsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="email_utilisateur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mdp_utilisateur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *               &lt;minLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="type_utilisateur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="admin"/>
 *               &lt;enumeration value="client"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nom_utilisateur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prenom_utilisateur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enregistrementsType", propOrder = {
    "emailUtilisateur",
    "mdpUtilisateur",
    "typeUtilisateur",
    "nomUtilisateur",
    "prenomUtilisateur"
})
public class EnregistrementsType {

    @XmlElement(name = "email_utilisateur", required = true)
    protected String emailUtilisateur;
    @XmlElement(name = "mdp_utilisateur", required = true)
    protected String mdpUtilisateur;
    @XmlElement(name = "type_utilisateur", required = true)
    protected String typeUtilisateur;
    @XmlElement(name = "nom_utilisateur", required = true)
    protected String nomUtilisateur;
    @XmlElement(name = "prenom_utilisateur", required = true)
    protected String prenomUtilisateur;

    /**
     * Gets the value of the emailUtilisateur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailUtilisateur() {
        return emailUtilisateur;
    }

    /**
     * Sets the value of the emailUtilisateur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailUtilisateur(String value) {
        this.emailUtilisateur = value;
    }

    /**
     * Gets the value of the mdpUtilisateur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdpUtilisateur() {
        return mdpUtilisateur;
    }

    /**
     * Sets the value of the mdpUtilisateur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdpUtilisateur(String value) {
        this.mdpUtilisateur = value;
    }

    /**
     * Gets the value of the typeUtilisateur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeUtilisateur() {
        return typeUtilisateur;
    }

    /**
     * Sets the value of the typeUtilisateur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeUtilisateur(String value) {
        this.typeUtilisateur = value;
    }

    /**
     * Gets the value of the nomUtilisateur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomUtilisateur() {
        return nomUtilisateur;
    }

    /**
     * Sets the value of the nomUtilisateur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomUtilisateur(String value) {
        this.nomUtilisateur = value;
    }

    /**
     * Gets the value of the prenomUtilisateur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrenomUtilisateur() {
        return prenomUtilisateur;
    }

    /**
     * Sets the value of the prenomUtilisateur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrenomUtilisateur(String value) {
        this.prenomUtilisateur = value;
    }

}
